# Generated by Django 4.2.6 on 2023-10-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='groups',
            field=models.ManyToManyField(related_name='clientes', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='user_permissions',
            field=models.ManyToManyField(related_name='clientes', to='auth.permission'),
        ),
    ]
