# Generated by Django 4.2.7 on 2023-11-30 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_delete_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendedor',
            name='disponibilidade',
        ),
    ]
