# Generated by Django 4.2.7 on 2023-11-30 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_produto_quantidade_alter_produto_sabor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='sabor',
            field=models.CharField(choices=[('chocolate', 'Chocolate'), ('doce_de_leite', 'Doce de leite'), ('morango', 'Morango')], max_length=20),
        ),
    ]
